export const CONVERSATION_REPOSITORY = Symbol('CONVERSATION_REPOSITORY');
export const MESSAGE_REPOSITORY = Symbol('MESSAGE_REPOSITORY');
export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');
export const TRANSACTION_MANAGER = Symbol('TRANSACTION_MANAGER');
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');

