listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
relay-ip=0.0.0.0
external-ip=0.0.0.0
realm=zalo.local
server-name=zalo-turn

lt-cred-mech
user=zalo:zalosecret

total-quota=100
stale-nonce=600

no-cli
fingerprint
mobility
no-multicast-peers

max-bps=1024000
